import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CornerLayout from "./components/ux/corner/cornerLayout";
import Nav from "./components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="p-2 lg:p-0 grid grid-cols-[.1fr,1fr,1fr,1fr,.1fr] grid-rows-10 gap-4 lg:grid-cols-[0.5fr,1fr,1fr,1fr,1fr,1fr,1fr,1fr,0.5fr] lg:grid-rows-[0.5fr,1fr,1fr,1fr,0.5fr] w-full h-dvh overflow-hidden relative ">
          <CornerLayout />
          <Nav />
          {children}
        </section>
      </body>
    </html>
  );
}
